
//  Format: zohoApiSamples[app][endpointName] = { scope, method, url, params, headers, body }


const zohoApiSamples = {
  crm: {
    "Get Contacts":         { scope: "ZohoCRM.modules.READ",         method: "GET",    url: "https://www.zohoapis.com/crm/v2/Contacts",                          params: { page: 1, per_page: 200 },                      headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Contact By ID":    { scope: "ZohoCRM.modules.READ",         method: "GET",    url: "https://www.zohoapis.com/crm/v2/Contacts/{record_id}",              params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Contact":       { scope: "ZohoCRM.modules.CREATE",       method: "POST",   url: "https://www.zohoapis.com/crm/v2/Contacts",                          params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ First_Name: "John", Last_Name: "Doe", Email: "john.doe@example.com", Phone: "1234567890", Account_Name: "ABC Corp" }] } },
    "Update Contact":       { scope: "ZohoCRM.modules.UPDATE",       method: "PUT",    url: "https://www.zohoapis.com/crm/v2/Contacts/{record_id}",              params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ id: "{record_id}", Phone: "9876543210" }] } },
    "Delete Contact":       { scope: "ZohoCRM.modules.DELETE",       method: "DELETE", url: "https://www.zohoapis.com/crm/v2/Contacts/{record_id}",              params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Leads":            { scope: "ZohoCRM.modules.READ",         method: "GET",    url: "https://www.zohoapis.com/crm/v2/Leads",                             params: { page: 1, per_page: 200 },                      headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Lead":          { scope: "ZohoCRM.modules.CREATE",       method: "POST",   url: "https://www.zohoapis.com/crm/v2/Leads",                             params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ Last_Name: "Smith", Company: "ABC Corp", Email: "smith@example.com", Phone: "1234567890", Lead_Source: "Web Site" }] } },
    "Convert Lead":         { scope: "ZohoCRM.modules.UPDATE",       method: "POST",   url: "https://www.zohoapis.com/crm/v2/Leads/{record_id}/actions/convert", params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ overwrite: true, notify_lead_owner: true, Deals: { Deal_Name: "New Deal", Closing_Date: "2024-12-31", Stage: "Qualification", Amount: 5000 } }] } },
    "Get Deals":            { scope: "ZohoCRM.modules.READ",         method: "GET",    url: "https://www.zohoapis.com/crm/v2/Deals",                             params: { page: 1, per_page: 200 },                      headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Deal":          { scope: "ZohoCRM.modules.CREATE",       method: "POST",   url: "https://www.zohoapis.com/crm/v2/Deals",                             params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ Deal_Name: "Big Deal", Stage: "Proposal/Price Quote", Closing_Date: "2024-12-31", Amount: 15000, Account_Name: { name: "ABC Corp" } }] } },
    "Get Accounts":         { scope: "ZohoCRM.modules.READ",         method: "GET",    url: "https://www.zohoapis.com/crm/v2/Accounts",                          params: { page: 1, per_page: 200 },                      headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Account":       { scope: "ZohoCRM.modules.CREATE",       method: "POST",   url: "https://www.zohoapis.com/crm/v2/Accounts",                          params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ Account_Name: "Tech Corp", Website: "https://techcorp.com", Phone: "1234567890", Industry: "Technology", Annual_Revenue: 1000000 }] } },
    "Get Tasks":            { scope: "ZohoCRM.modules.READ",         method: "GET",    url: "https://www.zohoapis.com/crm/v2/Tasks",                             params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Task":          { scope: "ZohoCRM.modules.CREATE",       method: "POST",   url: "https://www.zohoapis.com/crm/v2/Tasks",                             params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ Subject: "Follow up call", Status: "Not Started", Due_Date: "2024-12-31", What_Id: { id: "{deal_id}" } }] } },
    "Get Notes":            { scope: "ZohoCRM.modules.READ",         method: "GET",    url: "https://www.zohoapis.com/crm/v2/Notes",                             params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Note":          { scope: "ZohoCRM.modules.CREATE",       method: "POST",   url: "https://www.zohoapis.com/crm/v2/Notes",                             params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ Note_Title: "Meeting summary", Note_Content: "Discussed pricing", Parent_Id: { id: "{record_id}" }, se_module: "Contacts" }] } },
    "Get Users":            { scope: "ZohoCRM.users.READ",           method: "GET",    url: "https://www.zohoapis.com/crm/v2/users",                             params: { type: "AllUsers" },                            headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Organization":     { scope: "ZohoCRM.org.READ",             method: "GET",    url: "https://www.zohoapis.com/crm/v2/org",                               params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Search Records":       { scope: "ZohoCRM.modules.READ",         method: "GET",    url: "https://www.zohoapis.com/crm/v2/Contacts/search",                   params: { criteria: "(Email:equals:john@example.com)" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "COQL Query":           { scope: "ZohoCRM.coql.READ",            method: "POST",   url: "https://www.zohoapis.com/crm/v2/coql",                              params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { select_query: "select Last_Name, First_Name, Email from Contacts where Email is not null limit 10" } },
    "Get Modules":          { scope: "ZohoCRM.settings.READ",        method: "GET",    url: "https://www.zohoapis.com/crm/v2/settings/modules",                  params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Fields":           { scope: "ZohoCRM.settings.READ",        method: "GET",    url: "https://www.zohoapis.com/crm/v2/settings/fields",                   params: { module: "Contacts" },                          headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Bulk Upsert Records":  { scope: "ZohoCRM.bulk.CREATE",          method: "POST",   url: "https://www.zohoapis.com/crm/v2/Contacts/upsert",                   params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ First_Name: "Alice", Last_Name: "Brown", Email: "alice@example.com" }], duplicate_check_fields: ["Email"] } },
    "Enable Notifications": { scope: "ZohoCRM.notifications.CREATE", method: "POST",   url: "https://www.zohoapis.com/crm/v2/actions/watch",                     params: {},                                              headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { watch: [{ channel_id: "1000000068001", events: ["Contacts.create", "Contacts.edit"], channel_expiry: "2024-12-31T00:00:00+05:30", notify_url: "https://your-domain.com/webhook", token: "VERIFY_TOKEN" }] } }
  },
  books: {
    "Get Organizations":     { scope: "ZohoBooks.settings.READ",        method: "GET",  url: "https://www.zohoapis.com/books/v3/organizations",               params: {},                                                        headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Contacts":          { scope: "ZohoBooks.contacts.READ",         method: "GET",  url: "https://www.zohoapis.com/books/v3/contacts",                    params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Contact":        { scope: "ZohoBooks.contacts.CREATE",       method: "POST", url: "https://www.zohoapis.com/books/v3/contacts",                    params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { contact_name: "John Doe", contact_type: "customer", email: "john@example.com", phone: "1234567890" } },
    "Get Invoices":          { scope: "ZohoBooks.invoices.READ",         method: "GET",  url: "https://www.zohoapis.com/books/v3/invoices",                    params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Invoice":        { scope: "ZohoBooks.invoices.CREATE",       method: "POST", url: "https://www.zohoapis.com/books/v3/invoices",                    params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { customer_id: "{customer_id}", date: "2024-01-15", due_date: "2024-02-14", line_items: [{ name: "Consulting Services", rate: 1000, quantity: 1 }] } },
    "Email Invoice":         { scope: "ZohoBooks.invoices.UPDATE",       method: "POST", url: "https://www.zohoapis.com/books/v3/invoices/{invoice_id}/email", params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { to_mail_ids: ["customer@example.com"], subject: "Invoice from Your Company" } },
    "Get Items":             { scope: "ZohoBooks.items.READ",            method: "GET",  url: "https://www.zohoapis.com/books/v3/items",                       params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Item":           { scope: "ZohoBooks.items.CREATE",          method: "POST", url: "https://www.zohoapis.com/books/v3/items",                       params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { name: "Consulting", description: "Hourly consulting rate", rate: 150, unit: "hrs" } },
    "Get Expenses":          { scope: "ZohoBooks.expenses.READ",         method: "GET",  url: "https://www.zohoapis.com/books/v3/expenses",                    params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Bills":             { scope: "ZohoBooks.bills.READ",            method: "GET",  url: "https://www.zohoapis.com/books/v3/bills",                       params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Purchase Orders":   { scope: "ZohoBooks.purchaseorders.READ",   method: "GET",  url: "https://www.zohoapis.com/books/v3/purchaseorders",              params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Sales Orders":      { scope: "ZohoBooks.salesorders.READ",      method: "GET",  url: "https://www.zohoapis.com/books/v3/salesorders",                 params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Chart of Accounts": { scope: "ZohoBooks.chartofaccounts.READ",  method: "GET",  url: "https://www.zohoapis.com/books/v3/chartofaccounts",             params: { organization_id: "{org_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Balance Sheet":     { scope: "ZohoBooks.reports.READ",          method: "GET",  url: "https://www.zohoapis.com/books/v3/reports/balancesheet",         params: { organization_id: "{org_id}", date: "2024-12-31" },       headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Profit and Loss":   { scope: "ZohoBooks.reports.READ",          method: "GET",  url: "https://www.zohoapis.com/books/v3/reports/profitandloss",        params: { organization_id: "{org_id}", from_date: "2024-01-01", to_date: "2024-12-31" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  desk: {
    "Get Tickets":        { scope: "Desk.tickets.READ",     method: "GET",    url: "https://desk.zoho.com/api/v1/tickets",                             params: { limit: 50, from: 0 },                         headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: null },
    "Get Ticket By ID":   { scope: "Desk.tickets.READ",     method: "GET",    url: "https://desk.zoho.com/api/v1/tickets/{ticket_id}",                 params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: null },
    "Create Ticket":      { scope: "Desk.tickets.CREATE",   method: "POST",   url: "https://desk.zoho.com/api/v1/tickets",                             params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: { subject: "Issue with product", departmentId: "{dept_id}", contactId: "{contact_id}", description: "Detailed description", priority: "medium", status: "Open", channel: "Email" } },
    "Update Ticket":      { scope: "Desk.tickets.UPDATE",   method: "PATCH",  url: "https://desk.zoho.com/api/v1/tickets/{ticket_id}",                 params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: { status: "On Hold", priority: "high" } },
    "Delete Ticket":      { scope: "Desk.tickets.DELETE",   method: "DELETE", url: "https://desk.zoho.com/api/v1/tickets/{ticket_id}",                 params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: null },
    "Add Comment":        { scope: "Desk.tickets.CREATE",   method: "POST",   url: "https://desk.zoho.com/api/v1/tickets/{ticket_id}/comments",        params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: { content: "We are looking into this issue.", isPublic: true } },
    "Send Reply":         { scope: "Desk.tickets.UPDATE",   method: "POST",   url: "https://desk.zoho.com/api/v1/tickets/{ticket_id}/sendReply",       params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: { content: "Thank you for contacting us.", isPublic: true, channel: "EMAIL", to: [{ email: "customer@example.com" }] } },
    "Get Contacts":       { scope: "Desk.contacts.READ",    method: "GET",    url: "https://desk.zoho.com/api/v1/contacts",                            params: { limit: 50, from: 0 },                         headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: null },
    "Create Contact":     { scope: "Desk.contacts.CREATE",  method: "POST",   url: "https://desk.zoho.com/api/v1/contacts",                            params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: { lastName: "Doe", firstName: "John", email: "john@example.com", phone: "1234567890" } },
    "Get Agents":         { scope: "Desk.agents.READ",      method: "GET",    url: "https://desk.zoho.com/api/v1/agents",                              params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: null },
    "Get Departments":    { scope: "Desk.departments.READ", method: "GET",    url: "https://desk.zoho.com/api/v1/departments",                         params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: null },
    "Get Articles":       { scope: "Desk.articles.READ",    method: "GET",    url: "https://desk.zoho.com/api/v1/articles",                            params: {},                                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: null },
    "Search Tickets":     { scope: "Desk.search.READ",      method: "GET",    url: "https://desk.zoho.com/api/v1/search",                              params: { module: "tickets", searchStr: "billing issue" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json", orgId: "{org_id}" }, body: null }
  },
  mail: {
    "Get Accounts":  { scope: "ZohoMail.accounts.READ",   method: "GET",    url: "https://mail.zoho.com/api/accounts",                                                              params: {},                                     headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Folders":   { scope: "ZohoMail.folders.READ",    method: "GET",    url: "https://mail.zoho.com/api/accounts/{account_id}/folders",                                        params: {},                                     headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Messages":  { scope: "ZohoMail.messages.READ",   method: "GET",    url: "https://mail.zoho.com/api/accounts/{account_id}/messages/view",                                  params: { folderId: "{folder_id}", limit: 50 }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Send Email":    { scope: "ZohoMail.messages.CREATE", method: "POST",   url: "https://mail.zoho.com/api/accounts/{account_id}/messages",                                       params: {},                                     headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { fromAddress: "sender@example.com", toAddress: "recipient@example.com", subject: "Test Email", content: "Hello!", mailFormat: "html" } },
    "Delete Message":{ scope: "ZohoMail.messages.DELETE", method: "DELETE", url: "https://mail.zoho.com/api/accounts/{account_id}/folders/{folder_id}/messages/{message_id}",     params: {},                                     headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Search Emails": { scope: "ZohoMail.messages.READ",   method: "GET",    url: "https://mail.zoho.com/api/accounts/{account_id}/messages/search",                               params: { searchKey: "invoice", limit: 50 },    headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  projects: {
    "Get Portals":    { scope: "ZohoProjects.portals.READ",      method: "GET",  url: "https://projectsapi.zoho.com/restapi/portals/",                                                     params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Projects":   { scope: "ZohoProjects.projects.READ",     method: "GET",  url: "https://projectsapi.zoho.com/restapi/portal/{portal_id}/projects/",                                params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Project": { scope: "ZohoProjects.projects.CREATE",   method: "POST", url: "https://projectsapi.zoho.com/restapi/portal/{portal_id}/projects/",                                params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/x-www-form-urlencoded" }, body: "name=My+Project&start_date=01-15-2024&end_date=12-31-2024" },
    "Get Tasks":      { scope: "ZohoProjects.tasks.READ",        method: "GET",  url: "https://projectsapi.zoho.com/restapi/portal/{portal_id}/projects/{project_id}/tasks/",              params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Task":    { scope: "ZohoProjects.tasks.CREATE",      method: "POST", url: "https://projectsapi.zoho.com/restapi/portal/{portal_id}/projects/{project_id}/tasks/",              params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/x-www-form-urlencoded" }, body: "name=Design+Homepage&start_date=01-15-2024&priority=high" },
    "Get Milestones": { scope: "ZohoProjects.milestones.READ",   method: "GET",  url: "https://projectsapi.zoho.com/restapi/portal/{portal_id}/projects/{project_id}/milestones/",        params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Bugs":       { scope: "ZohoProjects.bugs.READ",         method: "GET",  url: "https://projectsapi.zoho.com/restapi/portal/{portal_id}/projects/{project_id}/bugs/",               params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Log Time":       { scope: "ZohoProjects.timesheets.CREATE", method: "POST", url: "https://projectsapi.zoho.com/restapi/portal/{portal_id}/projects/{project_id}/tasks/{task_id}/logs/", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/x-www-form-urlencoded" }, body: "date=01-15-2024&hours=2&minutes=30&billing_status=Billable" }
  },
  people: {
    "Get Employees":      { scope: "ZOHOPEOPLE.employee.READ",    method: "GET",  url: "https://people.zoho.com/people/api/forms/employee/getRecords",       params: { sIndex: 1, limit: 200 },                             headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Employee By ID": { scope: "ZOHOPEOPLE.employee.READ",    method: "GET",  url: "https://people.zoho.com/people/api/forms/employee/getDataByID",       params: { recordId: "{employee_id}" },                         headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Add Employee":       { scope: "ZOHOPEOPLE.employee.CREATE",  method: "POST", url: "https://people.zoho.com/people/api/forms/employee/insertRecord",       params: {},                                                    headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/x-www-form-urlencoded" }, body: "inputData=%7B%22First_Name%22%3A%22John%22%2C%22Last_Name%22%3A%22Doe%22%7D" },
    "Get Leave Types":    { scope: "ZOHOPEOPLE.leave.READ",       method: "GET",  url: "https://people.zoho.com/people/api/leave/getLeaveTypeDetails",         params: {},                                                    headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Leave Balance":  { scope: "ZOHOPEOPLE.leave.READ",       method: "GET",  url: "https://people.zoho.com/people/api/leave/getLeaveBalance",             params: { userId: "{employee_id}" },                           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Apply Leave":        { scope: "ZOHOPEOPLE.leave.CREATE",     method: "POST", url: "https://people.zoho.com/people/api/leave/addLeave",                    params: {},                                                    headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/x-www-form-urlencoded" }, body: "userId={employee_id}&leaveTypeId={leave_type_id}&from=01-15-2024&to=01-17-2024" },
    "Get Attendance":     { scope: "ZOHOPEOPLE.attendance.READ",  method: "GET",  url: "https://people.zoho.com/people/api/attendance/getUserReport",          params: { userId: "{employee_id}", from: "01-01-2024", to: "01-31-2024" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Departments":    { scope: "ZOHOPEOPLE.department.READ",  method: "GET",  url: "https://people.zoho.com/people/api/department",                        params: {},                                                    headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  recruit: {
    "Get Job Openings":   { scope: "ZohoRecruit.modules.READ",   method: "GET",  url: "https://recruit.zoho.com/recruit/v2/JobOpenings", params: { page: 1, per_page: 200 }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Job Opening": { scope: "ZohoRecruit.modules.CREATE", method: "POST", url: "https://recruit.zoho.com/recruit/v2/JobOpenings", params: {},                         headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ Posting_Title: "Senior Developer", Job_Type: "Full time", No_of_Positions: 2, Job_Status: "Open" }] } },
    "Get Candidates":     { scope: "ZohoRecruit.modules.READ",   method: "GET",  url: "https://recruit.zoho.com/recruit/v2/Candidates",  params: { page: 1, per_page: 200 }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Candidate":   { scope: "ZohoRecruit.modules.CREATE", method: "POST", url: "https://recruit.zoho.com/recruit/v2/Candidates",  params: {},                         headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ First_Name: "Jane", Last_Name: "Doe", Email: "jane@example.com", Experience_in_Years: 5 }] } },
    "Get Interviews":     { scope: "ZohoRecruit.modules.READ",   method: "GET",  url: "https://recruit.zoho.com/recruit/v2/Interviews",  params: { page: 1, per_page: 200 }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Schedule Interview": { scope: "ZohoRecruit.modules.CREATE", method: "POST", url: "https://recruit.zoho.com/recruit/v2/Interviews",  params: {},                         headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ Name: "Technical Interview", Candidate_Name: { id: "{candidate_id}" }, Scheduled_Time: "2024-02-01T10:00:00", Status: "Pending" }] } }
  },
  campaigns: {
    "Get Mailing Lists":   { scope: "ZohoCampaigns.list.READ",      method: "GET",  url: "https://campaigns.zoho.com/api/v1.1/getmailinglists",    params: { resfmt: "JSON", fromindex: 1, range: 50 },         headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Mailing List": { scope: "ZohoCampaigns.list.CREATE",    method: "POST", url: "https://campaigns.zoho.com/api/v1.1/addlist",            params: {},                                                  headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/x-www-form-urlencoded" }, body: "resfmt=JSON&listname=Newsletter+Subscribers" },
    "Add Contact to List": { scope: "ZohoCampaigns.contact.CREATE", method: "POST", url: "https://campaigns.zoho.com/api/v1.1/json/listsubscribe", params: {},                                                  headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/x-www-form-urlencoded" }, body: "resfmt=JSON&listkey={list_key}&contactinfo=%7B%22Contact+Email%22%3A%22john%40example.com%22%7D" },
    "Get Campaigns":       { scope: "ZohoCampaigns.campaign.READ",  method: "GET",  url: "https://campaigns.zoho.com/api/v1.1/getcampaigns",       params: { resfmt: "JSON", campaignstatus: "all" },           headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Campaign Report": { scope: "ZohoCampaigns.report.READ",    method: "GET",  url: "https://campaigns.zoho.com/api/v1.1/getreportbydate",    params: { resfmt: "JSON", campaignkey: "{campaign_key}" },  headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  inventory: {
    "Get Items":          { scope: "ZohoInventory.items.READ",         method: "GET",  url: "https://www.zohoapis.com/inventory/v1/items",        params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Item":        { scope: "ZohoInventory.items.CREATE",       method: "POST", url: "https://www.zohoapis.com/inventory/v1/items",        params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { name: "Laptop", sku: "LAPTOP-001", rate: 999.99, initial_stock: 50 } },
    "Get Sales Orders":   { scope: "ZohoInventory.salesorders.READ",   method: "GET",  url: "https://www.zohoapis.com/inventory/v1/salesorders", params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Sales Order": { scope: "ZohoInventory.salesorders.CREATE", method: "POST", url: "https://www.zohoapis.com/inventory/v1/salesorders", params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { customer_id: "{customer_id}", salesorder_number: "SO-001", line_items: [{ item_id: "{item_id}", quantity: 5, rate: 999.99 }] } },
    "Get Warehouses":     { scope: "ZohoInventory.warehouses.READ",    method: "GET",  url: "https://www.zohoapis.com/inventory/v1/warehouses",   params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  analytics: {
    "Get Workspaces": { scope: "ZohoAnalytics.workspace.READ", method: "GET",  url: "https://analyticsapi.zoho.com/api/v2/workspaces",                                            params: {},                                  headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Views":      { scope: "ZohoAnalytics.report.READ",    method: "GET",  url: "https://analyticsapi.zoho.com/api/v2/workspaces/{workspace_id}/views",                       params: {},                                  headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Data":       { scope: "ZohoAnalytics.data.READ",      method: "GET",  url: "https://analyticsapi.zoho.com/api/v2/workspaces/{workspace_id}/views/{view_id}/data",        params: { CONFIG: "{\"maximumRows\":200}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Add Row":        { scope: "ZohoAnalytics.data.CREATE",    method: "POST", url: "https://analyticsapi.zoho.com/api/v2/workspaces/{workspace_id}/views/{view_id}/rows",        params: {},                                  headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { CONFIG: "{}", columns: { Column1: "Value1" } } },
    "Export Data":    { scope: "ZohoAnalytics.data.READ",      method: "GET",  url: "https://analyticsapi.zoho.com/api/v2/workspaces/{workspace_id}/views/{view_id}/export",      params: { CONFIG: "{\"fileType\":\"csv\"}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  sign: {
    "Get Documents":       { scope: "ZohoSign.documents.READ",   method: "GET",  url: "https://sign.zoho.com/api/v1/requests",                              params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Document Status": { scope: "ZohoSign.documents.READ",   method: "GET",  url: "https://sign.zoho.com/api/v1/requests/{request_id}",                 params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Download Signed PDF": { scope: "ZohoSign.documents.READ",   method: "GET",  url: "https://sign.zoho.com/api/v1/requests/{request_id}/pdf",             params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Revoke Document":     { scope: "ZohoSign.documents.UPDATE", method: "POST", url: "https://sign.zoho.com/api/v1/requests/{request_id}/revoke",          params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { reason: "Document revision required" } },
    "Get Templates":       { scope: "ZohoSign.templates.READ",   method: "GET",  url: "https://sign.zoho.com/api/v1/templates",                             params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  workdrive: {
    "Get Teams":         { scope: "WorkDrive.teams.READ",     method: "GET",    url: "https://workdrive.zoho.com/api/v1/teams",                   params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Workspaces":    { scope: "WorkDrive.workspace.READ", method: "GET",    url: "https://workdrive.zoho.com/api/v1/workspaces",              params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Files":         { scope: "WorkDrive.files.READ",     method: "GET",    url: "https://workdrive.zoho.com/api/v1/files/{folder_id}/files", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Folder":     { scope: "WorkDrive.files.CREATE",   method: "POST",   url: "https://workdrive.zoho.com/api/v1/files",                   params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: { attributes: { name: "New Folder", parent_id: "{parent_id}" }, type: "files" } } },
    "Delete File":       { scope: "WorkDrive.files.DELETE",   method: "DELETE", url: "https://workdrive.zoho.com/api/v1/files/{file_id}",         params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Share Link": { scope: "WorkDrive.links.CREATE",   method: "POST",   url: "https://workdrive.zoho.com/api/v1/links",                   params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: { attributes: { resource_id: "{file_id}", resource_type: "files", link_type: "1" } } } }
  },
  cliq: {
    "Get Channels":         { scope: "ZohoCliq.channels.READ",  method: "GET",  url: "https://cliq.zoho.com/api/v2/channels",                                     params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Channel":       { scope: "ZohoCliq.channels.CREATE",method: "POST", url: "https://cliq.zoho.com/api/v2/channels",                                     params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { name: "project-updates", description: "Channel for project updates", type: "open" } },
    "Send Channel Message": { scope: "ZohoCliq.messages.CREATE",method: "POST", url: "https://cliq.zoho.com/api/v2/channels/{channel_unique_name}/message",        params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { text: "Hello Team! Updates are live." } },
    "Send Direct Message":  { scope: "ZohoCliq.messages.CREATE",method: "POST", url: "https://cliq.zoho.com/api/v2/chats/{chat_id}/message",                      params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { text: "Hey, can we chat?" } },
    "Get Contacts":         { scope: "ZohoCliq.contacts.READ",  method: "GET",  url: "https://cliq.zoho.com/api/v2/contacts",                                     params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  creator: {
    "Get Applications": { scope: "ZohoCreator.meta.READ",    method: "GET",    url: "https://creator.zoho.com/api/v2/applications",                                                                 params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Records":      { scope: "ZohoCreator.report.READ",  method: "GET",    url: "https://creator.zoho.com/api/v2/{owner_name}/{app_link_name}/report/{report_link_name}",                       params: { from: 1, limit: 200 }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Add Record":       { scope: "ZohoCreator.form.CREATE",  method: "POST",   url: "https://creator.zoho.com/api/v2/{owner_name}/{app_link_name}/form/{form_link_name}",                           params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: { Name: "John Doe", Email: "john@example.com", Status: "Active" } } },
    "Update Record":    { scope: "ZohoCreator.report.UPDATE",method: "PATCH",  url: "https://creator.zoho.com/api/v2/{owner_name}/{app_link_name}/report/{report_link_name}/{record_id}",           params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: { Status: "Inactive" } } },
    "Delete Record":    { scope: "ZohoCreator.report.DELETE",method: "DELETE", url: "https://creator.zoho.com/api/v2/{owner_name}/{app_link_name}/report/{report_link_name}/{record_id}",           params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  social: {
    "Get Portals":     { scope: "ZohoSocial.portals.READ",    method: "GET",  url: "https://social.zoho.com/api/v1/portals",                 params: {},                                       headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Connections": { scope: "ZohoSocial.connections.READ",method: "GET",  url: "https://social.zoho.com/api/v1/{portal_id}/connections",params: {},                                       headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Schedule Post":   { scope: "ZohoSocial.publish.CREATE",  method: "POST", url: "https://social.zoho.com/api/v1/{portal_id}/post",       params: {},                                       headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { content: "Check out our new product launch!", scheduleTime: "2024-02-01T10:00:00Z", connections: [{ connectionId: "{connection_id}", connectionType: "facebook" }] } },
    "Publish Now":     { scope: "ZohoSocial.publish.CREATE",  method: "POST", url: "https://social.zoho.com/api/v1/{portal_id}/post",       params: {},                                       headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { content: "We just launched!", publishNow: true, connections: [{ connectionId: "{connection_id}", connectionType: "twitter" }] } },
    "Get Reports":     { scope: "ZohoSocial.reports.READ",    method: "GET",  url: "https://social.zoho.com/api/v1/{portal_id}/reports",    params: { from: "2024-01-01", to: "2024-01-31" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  meeting: {
    "Get Meetings":   { scope: "ZohoMeeting.meeting.READ",   method: "GET",    url: "https://meeting.zoho.com/api/v1/{org_id}/sessions",                        params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Meeting": { scope: "ZohoMeeting.meeting.CREATE", method: "POST",   url: "https://meeting.zoho.com/api/v1/{org_id}/sessions",                        params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { topic: "Weekly Team Sync", start_time: "2024-02-01T10:00:00Z", duration: 60, timezone: "America/New_York" } },
    "Delete Meeting": { scope: "ZohoMeeting.meeting.DELETE", method: "DELETE", url: "https://meeting.zoho.com/api/v1/{org_id}/sessions/{meeting_id}",           params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Webinar": { scope: "ZohoMeeting.webinar.CREATE", method: "POST",   url: "https://meeting.zoho.com/api/v1/{org_id}/webinars",                        params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { topic: "Product Launch Webinar", start_time: "2024-03-15T14:00:00Z", duration: 90 } },
    "Get Recordings": { scope: "ZohoMeeting.recording.READ", method: "GET",    url: "https://meeting.zoho.com/api/v1/{org_id}/sessions/{meeting_id}/recordings", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  survey: {
    "Get Surveys":       { scope: "ZohoSurvey.surveys.READ",   method: "GET",  url: "https://survey.zoho.com/api/v1/surveys",                       params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Survey":     { scope: "ZohoSurvey.surveys.CREATE", method: "POST", url: "https://survey.zoho.com/api/v1/surveys",                       params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { surveyname: "Customer Satisfaction Survey", language: "en" } },
    "Get Responses":     { scope: "ZohoSurvey.responses.READ", method: "GET",  url: "https://survey.zoho.com/api/v1/surveys/{survey_id}/responses", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Survey Report": { scope: "ZohoSurvey.reports.READ",   method: "GET",  url: "https://survey.zoho.com/api/v1/surveys/{survey_id}/report",    params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  expense: {
    "Get Expenses":          { scope: "ZohoExpense.expense.READ",   method: "GET",  url: "https://expense.zoho.com/api/v1/expenses",                          params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Expense":        { scope: "ZohoExpense.expense.CREATE", method: "POST", url: "https://expense.zoho.com/api/v1/expenses",                          params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { expense_date: "2024-01-15", account_id: "{account_id}", total: 150.00, description: "Team lunch" } },
    "Get Expense Reports":   { scope: "ZohoExpense.reports.READ",   method: "GET",  url: "https://expense.zoho.com/api/v1/expensereports",                    params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Expense Report": { scope: "ZohoExpense.reports.CREATE", method: "POST", url: "https://expense.zoho.com/api/v1/expensereports",                    params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { report_name: "January 2024 Expenses", start_date: "2024-01-01", end_date: "2024-01-31" } },
    "Submit Report":         { scope: "ZohoExpense.reports.UPDATE", method: "POST", url: "https://expense.zoho.com/api/v1/expensereports/{report_id}/submit", params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  subscriptions: {
    "Get Customers":       { scope: "ZohoSubscriptions.customers.READ",       method: "GET",  url: "https://www.zohoapis.com/billing/v1/customers",                                params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Customer":     { scope: "ZohoSubscriptions.customers.CREATE",     method: "POST", url: "https://www.zohoapis.com/billing/v1/customers",                                params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { display_name: "Tech Corp", email: "billing@techcorp.com" } },
    "Get Plans":           { scope: "ZohoSubscriptions.plans.READ",           method: "GET",  url: "https://www.zohoapis.com/billing/v1/plans",                                   params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Subscriptions":   { scope: "ZohoSubscriptions.subscriptions.READ",   method: "GET",  url: "https://www.zohoapis.com/billing/v1/subscriptions",                           params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Subscription": { scope: "ZohoSubscriptions.subscriptions.CREATE", method: "POST", url: "https://www.zohoapis.com/billing/v1/subscriptions",                           params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { customer_id: "{customer_id}", plan: { plan_code: "monthly-pro", quantity: 1 } } },
    "Cancel Subscription": { scope: "ZohoSubscriptions.subscriptions.UPDATE", method: "POST", url: "https://www.zohoapis.com/billing/v1/subscriptions/{subscription_id}/cancel",  params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { cancel_at_end: true } },
    "Get Invoices":        { scope: "ZohoSubscriptions.invoices.READ",        method: "GET",  url: "https://www.zohoapis.com/billing/v1/invoices",                                params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  payroll: {
    "Get Employees":   { scope: "ZohoPayroll.employees.READ",  method: "GET",  url: "https://payroll.zoho.com/api/v1/employees",              params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Employee": { scope: "ZohoPayroll.employees.CREATE",method: "POST", url: "https://payroll.zoho.com/api/v1/employees",              params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { first_name: "John", last_name: "Doe", email: "john@company.com", date_of_joining: "2024-01-15", designation: "Software Engineer" } },
    "Get Pay Runs":    { scope: "ZohoPayroll.payrun.READ",     method: "GET",  url: "https://payroll.zoho.com/api/v1/payruns",                params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Pay Run":  { scope: "ZohoPayroll.payrun.CREATE",   method: "POST", url: "https://payroll.zoho.com/api/v1/payruns",                params: { organization_id: "{org_id}" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { pay_schedule_id: "{schedule_id}", start_date: "2024-01-01", end_date: "2024-01-31" } }
  },
  sprints: {
    "Get Teams":        { scope: "ZohoSprints.projects.READ",  method: "GET",  url: "https://sprints.zoho.com/apiv2/teams",                                                            params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Projects":     { scope: "ZohoSprints.projects.READ",  method: "GET",  url: "https://sprints.zoho.com/apiv2/teams/{team_id}/projects",                                        params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Sprints":      { scope: "ZohoSprints.sprints.READ",   method: "GET",  url: "https://sprints.zoho.com/apiv2/teams/{team_id}/projects/{project_id}/sprints",                   params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Sprint":    { scope: "ZohoSprints.sprints.CREATE", method: "POST", url: "https://sprints.zoho.com/apiv2/teams/{team_id}/projects/{project_id}/sprints",                   params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { name: "Sprint 1", startdate: "01-15-2024", enddate: "01-29-2024" } },
    "Get Work Items":   { scope: "ZohoSprints.items.READ",     method: "GET",  url: "https://sprints.zoho.com/apiv2/teams/{team_id}/projects/{project_id}/sprints/{sprint_id}/item", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Work Item": { scope: "ZohoSprints.items.CREATE",   method: "POST", url: "https://sprints.zoho.com/apiv2/teams/{team_id}/projects/{project_id}/sprints/{sprint_id}/item", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { name: "Design product page", priority: "High", storypoints: 5, type: "story" } }
  },
  salesiq: {
    "Get Conversations": { scope: "SalesIQ.conversations.READ", method: "GET", url: "https://salesiq.zoho.com/api/v2/{portal_name}/conversations", params: {},                                       headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Visitors":      { scope: "SalesIQ.visitors.READ",      method: "GET", url: "https://salesiq.zoho.com/api/v2/{portal_name}/visitors",      params: { status: "online" },                     headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Contacts":      { scope: "SalesIQ.contacts.READ",      method: "GET", url: "https://salesiq.zoho.com/api/v2/{portal_name}/contacts",      params: {},                                       headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Agents":        { scope: "SalesIQ.agents.READ",        method: "GET", url: "https://salesiq.zoho.com/api/v2/{portal_name}/operators",     params: {},                                       headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Chat Reports":  { scope: "SalesIQ.reports.READ",       method: "GET", url: "https://salesiq.zoho.com/api/v2/{portal_name}/reports/chats", params: { from: "2024-01-01", to: "2024-01-31" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  vault: {
    "Get Secrets":   { scope: "ZohoVault.secrets.READ",   method: "GET",    url: "https://vault.zoho.com/api/v1/secrets",              params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Secret": { scope: "ZohoVault.secrets.CREATE", method: "POST",   url: "https://vault.zoho.com/api/v1/secrets",              params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { secretname: "AWS API Key", secretvalue: "AKIAIOSFODNN7EXAMPLE", note: "Production key" } },
    "Update Secret": { scope: "ZohoVault.secrets.UPDATE", method: "PUT",    url: "https://vault.zoho.com/api/v1/secrets/{secret_id}", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { secretvalue: "NEWVALUE123456" } },
    "Delete Secret": { scope: "ZohoVault.secrets.DELETE", method: "DELETE", url: "https://vault.zoho.com/api/v1/secrets/{secret_id}", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Folders":   { scope: "ZohoVault.folders.READ",   method: "GET",    url: "https://vault.zoho.com/api/v1/folders",              params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  bigin: {
    "Get Contacts":  { scope: "ZohoBigin.modules.READ",   method: "GET",  url: "https://www.zohoapis.com/bigin/v1/Contacts",           params: {},                      headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Contact":{ scope: "ZohoBigin.modules.CREATE", method: "POST", url: "https://www.zohoapis.com/bigin/v1/Contacts",           params: {},                      headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { data: [{ First_Name: "John", Last_Name: "Doe", Email: "john@example.com" }] } },
    "Get Pipelines": { scope: "ZohoBigin.pipelines.READ", method: "GET",  url: "https://www.zohoapis.com/bigin/v1/settings/pipelines", params: { module: "Pipelines" }, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Deals":     { scope: "ZohoBigin.modules.READ",   method: "GET",  url: "https://www.zohoapis.com/bigin/v1/Pipelines",          params: {},                      headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  fsm: {
    "Get Work Orders":      { scope: "ZohoFSM.workorders.READ",      method: "GET",   url: "https://fsm.zoho.com/api/v1/workorders",                params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Work Order":    { scope: "ZohoFSM.workorders.CREATE",    method: "POST",  url: "https://fsm.zoho.com/api/v1/workorders",                params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { subject: "HVAC Maintenance", status: "New", priority: "Medium", scheduled_date: "2024-02-15" } },
    "Get Service Requests": { scope: "ZohoFSM.servicerequests.READ", method: "GET",   url: "https://fsm.zoho.com/api/v1/servicerequests",           params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Assets":           { scope: "ZohoFSM.assets.READ",          method: "GET",   url: "https://fsm.zoho.com/api/v1/assets",                    params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Assign Technician":    { scope: "ZohoFSM.workorders.UPDATE",    method: "PATCH", url: "https://fsm.zoho.com/api/v1/workorders/{workorder_id}", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { technician_id: "{agent_id}", status: "Assigned" } }
  },
  connect: {
    "Get Groups":     { scope: "ZohoConnect.groups.READ",   method: "GET",  url: "https://connect.zoho.com/api/v1/{network_id}/groups",  params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Group":   { scope: "ZohoConnect.groups.CREATE", method: "POST", url: "https://connect.zoho.com/api/v1/{network_id}/groups",  params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { groupName: "Marketing Team", description: "Group for marketing", isPrivate: false } },
    "Post to Stream": { scope: "ZohoConnect.streams.CREATE",method: "POST", url: "https://connect.zoho.com/api/v1/{network_id}/streams", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { message: "Company announcement: new product launching!" } },
    "Get Events":     { scope: "ZohoConnect.events.READ",   method: "GET",  url: "https://connect.zoho.com/api/v1/{network_id}/events",  params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  backstage: {
    "Get Events":    { scope: "ZohoBackstage.events.READ",    method: "GET",  url: "https://backstage.zoho.com/api/v1/portal/{portal_id}/events",                      params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Create Event":  { scope: "ZohoBackstage.events.CREATE",  method: "POST", url: "https://backstage.zoho.com/api/v1/portal/{portal_id}/events",                      params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { title: "TechConf 2024", startdate: "2024-06-15T09:00:00Z", enddate: "2024-06-17T18:00:00Z", event_type: "inperson" } },
    "Get Attendees": { scope: "ZohoBackstage.attendees.READ", method: "GET",  url: "https://backstage.zoho.com/api/v1/portal/{portal_id}/events/{event_id}/attendees", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Tickets":   { scope: "ZohoBackstage.tickets.READ",   method: "GET",  url: "https://backstage.zoho.com/api/v1/portal/{portal_id}/events/{event_id}/tickets",   params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  flow: {
    "Get Flows":       { scope: "ZohoFlow.flows.READ",       method: "GET",  url: "https://flow.zoho.com/api/v1/{org_id}/flows",           params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Get Flow By ID":  { scope: "ZohoFlow.flows.READ",       method: "GET",  url: "https://flow.zoho.com/api/v1/{org_id}/flows/{flow_id}", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null },
    "Enable Flow":     { scope: "ZohoFlow.flows.UPDATE",     method: "PATCH",url: "https://flow.zoho.com/api/v1/{org_id}/flows/{flow_id}", params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: { enabled: true } },
    "Get Connections": { scope: "ZohoFlow.connections.READ", method: "GET",  url: "https://flow.zoho.com/api/v1/{org_id}/connections",     params: {}, headers: { Authorization: "Zoho-oauthtoken <access_token>", "Content-Type": "application/json" }, body: null }
  },
  oauth: {
    "Authorization URL":                     { scope: "N/A", method: "GET",  url: "https://accounts.zoho.com/oauth/v2/auth",         params: { response_type: "code", client_id: "{your_client_id}", scope: "ZohoCRM.modules.ALL", redirect_uri: "https://your-app.com/callback", access_type: "offline", prompt: "consent" }, headers: {}, body: null },
    "Exchange Code for Token":               { scope: "N/A", method: "POST", url: "https://accounts.zoho.com/oauth/v2/token",        params: {}, headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: { code: "{authorization_code}", client_id: "{your_client_id}", client_secret: "{your_client_secret}", redirect_uri: "https://your-app.com/callback", grant_type: "authorization_code" } },
    "Refresh Access Token":                  { scope: "N/A", method: "POST", url: "https://accounts.zoho.com/oauth/v2/token",        params: {}, headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: { refresh_token: "{your_refresh_token}", client_id: "{your_client_id}", client_secret: "{your_client_secret}", grant_type: "refresh_token" } },
    "Client Credentials (Server-to-Server)": { scope: "N/A", method: "POST", url: "https://accounts.zoho.com/oauth/v2/token",        params: {}, headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: { client_id: "{your_client_id}", client_secret: "{your_client_secret}", grant_type: "client_credentials", scope: "ZohoCRM.modules.ALL" } },
    "Revoke Token":                          { scope: "N/A", method: "POST", url: "https://accounts.zoho.com/oauth/v2/token/revoke", params: {}, headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: { token: "{access_or_refresh_token}" } },
    "Token Info":                            { scope: "N/A", method: "GET",  url: "https://accounts.zoho.com/oauth/v2/tokeninfo",    params: { access_token: "{access_token}" }, headers: {}, body: null }
  }
};